
spring:
  datasource:
    name: back
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      # 配置监控统计拦截的filters（不配置则监控界面sql无法统计），监控统计filter:stat，日志filter:log4j，防御sql注入filter:wall
      filters: stat
      # 支持合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql(Sql合并)功能；慢SQL记录(配置超过5秒就是慢，默认是3秒)
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://192.168.195.130:3306/shiro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: admin1250
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 10
      #获取连接等待超时时间
      max-wait: 60000
      #检测连接的间隔时间，若连接空闲时间 >= minEvictableIdleTimeMillis，则关闭物理连接
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间(ms)
      min-evictable-idle-time-millis: 300000
      #用来检测连接是否有效的sql
      validation-query:  SELECT 1 FROM dual
      # 申请连接时检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效（不影响性能）
      test-while-idle: true
      # 申请连接时不检测连接是否有效
      test-on-borrow: false
      # 归还连接时不检测连接是否有效
      test-on-return: false
      #开启缓存preparedStatement(PSCache)，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      #启用PSCache后，指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.jett.example.util.model.One2Many

#控制台打印sql语句，level后面是dao包的路径
logging:
  level:
    com:
      jett:
        example:
          dao: debug
server:
  port: 8083